config/routes.rb
Chef::Application.routes.draw do

  resources :advertisers
  resources :careers
  resources :contacts
  resources :developers
  resources :helps
  resources :how_it_works
  resources :teams       
  resources :abouts
    
  root :to => 'homes#index'

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index    
  end
end

app/controllers/advertisers_controller.rb
class AdvertisersController < ApplicationController
  def index    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def index    
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index    
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index    
  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  def index    
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index    
  end
  
end

app/controllers/how_it_works_controller.rb
class HowItWorksController < ApplicationController
  def index    
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index    
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/how_it_works_helper.rb
module HowItWorksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/abouts/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </a>
      
      <div class="container-fluid nav-collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
           

        
        
        <ul class="nav nav-pills">
                <li><%=link_to "Chef Tutors", root_url %></li>   
                <li><%=link_to "About", abouts_path %></li>               
                <li><%=link_to "How It Works", how_it_works_path %></li>  
                <li><%=link_to "Advertisers", advertisers_path %></li>                
                <li><%=link_to "Developers", developers_path %></li>  
                <li><%=link_to "Careers", careers_path %></li>               
                <li><%=link_to "Team", teams_path %></li>  
                <li><%=link_to "Press", "#" %></li>             
                <li><%=link_to "Contact", contacts_path %></li>  
                <li><%=link_to "Help", helps_path %></li>                     
            
        </ul>          

            
     
        <ul class="nav nav-pills pull-right">           
              
                <li > <%= link_to 'Sign In', "#" %> </li>                
                <li > <%= link_to 'Sign Up', "#" %> </li>      

                
        </ul> 
      
      
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="hero-unit">
  <h1>"About Us"</h1>
  <p>Tagline</p>
  <p>
    <a class="btn btn-primary btn-large">
      Learn more
    </a>
  </p>
</div>

app/views/careers/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </a>
      
      <div class="container-fluid nav-collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
           

        
        
        <ul class="nav nav-pills">
                <li><%=link_to "Chef Tutors", root_url %></li>   
                <li><%=link_to "About", abouts_path %></li>               
                <li><%=link_to "How It Works", how_it_works_path %></li>  
                <li><%=link_to "Advertisers", advertisers_path %></li>                
                <li><%=link_to "Developers", developers_path %></li>  
                <li><%=link_to "Careers", careers_path %></li>               
                <li><%=link_to "Team", teams_path %></li>  
                <li><%=link_to "Press", "#" %></li>             
                <li><%=link_to "Contact", contacts_path %></li>  
                <li><%=link_to "Help", helps_path %></li>                     
            
        </ul>          

            
     
        <ul class="nav nav-pills pull-right">           
              
                <li > <%= link_to 'Sign In', "#" %> </li>                
                <li > <%= link_to 'Sign Up', "#" %> </li>      

                
        </ul> 
      
      
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="hero-unit">
  <h1>"Careers"</h1>
  <p>Tagline</p>
  <p>
    <a class="btn btn-primary btn-large">
      Learn more
    </a>
  </p>
</div>

app/views/contacts/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </a>
      
      <div class="container-fluid nav-collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
           

        
        
        <ul class="nav nav-pills">
                <li><%=link_to "Chef Tutors", root_url %></li>   
                <li><%=link_to "About", abouts_path %></li>               
                <li><%=link_to "How It Works", how_it_works_path %></li>  
                <li><%=link_to "Advertisers", advertisers_path %></li>                
                <li><%=link_to "Developers", developers_path %></li>  
                <li><%=link_to "Careers", careers_path %></li>               
                <li><%=link_to "Team", teams_path %></li>  
                <li><%=link_to "Press", "#" %></li>             
                <li><%=link_to "Contact", contacts_path %></li>  
                <li><%=link_to "Help", helps_path %></li>                     
            
        </ul>          

            
     
        <ul class="nav nav-pills pull-right">           
              
                <li > <%= link_to 'Sign In', "#" %> </li>                
                <li > <%= link_to 'Sign Up', "#" %> </li>      

                
        </ul> 
      
      
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="hero-unit">
  <h1>"Contact Us"</h1>
  <p>Tagline</p>
  <p>
    <a class="btn btn-primary btn-large">
      Learn more
    </a>
  </p>
</div>

app/views/developers/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </a>
      
      <div class="container-fluid nav-collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
           

        
        
        <ul class="nav nav-pills">
                <li><%=link_to "Chef Tutors", root_url %></li>   
                <li><%=link_to "About", abouts_path %></li>               
                <li><%=link_to "How It Works", how_it_works_path %></li>  
                <li><%=link_to "Advertisers", advertisers_path %></li>                
                <li><%=link_to "Developers", developers_path %></li>  
                <li><%=link_to "Careers", careers_path %></li>               
                <li><%=link_to "Team", teams_path %></li>  
                <li><%=link_to "Press", "#" %></li>             
                <li><%=link_to "Contact", contacts_path %></li>  
                <li><%=link_to "Help", helps_path %></li>                     
            
        </ul>          

            
     
        <ul class="nav nav-pills pull-right">           
              
                <li > <%= link_to 'Sign In', "#" %> </li>                
                <li > <%= link_to 'Sign Up', "#" %> </li>      

                
        </ul> 
      
      
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="hero-unit">
  <h1>"Developers"</h1>
  <p>Tagline</p>
  <p>
    <a class="btn btn-primary btn-large">
      Learn more
    </a>
  </p>
</div>

app/views/helps/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </a>
      
      <div class="container-fluid nav-collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
           

        
        
        <ul class="nav nav-pills">
                <li><%=link_to "Chef Tutors", root_url %></li>   
                <li><%=link_to "About", abouts_path %></li>               
                <li><%=link_to "How It Works", how_it_works_path %></li>  
                <li><%=link_to "Advertisers", advertisers_path %></li>                
                <li><%=link_to "Developers", developers_path %></li>  
                <li><%=link_to "Careers", careers_path %></li>               
                <li><%=link_to "Team", teams_path %></li>  
                <li><%=link_to "Press", "#" %></li>             
                <li><%=link_to "Contact", contacts_path %></li>  
                <li><%=link_to "Help", helps_path %></li>                     
            
        </ul>          

            
     
        <ul class="nav nav-pills pull-right">           
              
                <li > <%= link_to 'Sign In', "#" %> </li>                
                <li > <%= link_to 'Sign Up', "#" %> </li>      

                
        </ul> 
      
      
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="hero-unit">
  <h1>"Help "</h1>
  <p>Tagline</p>
  <p>
    <a class="btn btn-primary btn-large">
      Learn more
    </a>
  </p>
</div>

app/views/homes/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </a>
      
      <div class="container-fluid nav-collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
           

        
        
        <ul class="nav nav-pills">         
                <li><%=link_to "Work", "#" %></li>   
                <li><%=link_to "About", "#" %></li>               
                <li><%=link_to "Blog", "#" %></li>                        
                <li><%=link_to "Contact", "#" %></li>                            
            
        </ul>          
     
       
                   
     
      
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<!--/body -->


<div class="hero-unit">
  <center>
    <div class="input-append">
      <h1>"Search Your Favourites"</h1>
      <p>Tagline</p>
     <center> <input class="input-xxlarge" id="appendedInputButton" type="text" >
      <button class="btn" type="button">Search!</button></center>
    </div> 
  </center>
   
</div>

<div class = "container">
<div class="row-fluid">
  <div class="span12">
   
    <div class="row-fluid">
      <center>
      
      <ul class="thumbnails">
        <li class="span4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          </div>
        </li>
        
     
        <li class="span4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          </div>
        </li>
        
     
        <li class="span4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          </div>
        </li>
        
      </ul>
    </center>
    </div>
  </div>
</div>
</div>


<div class = "container">
<div class="row-fluid">
  <div class="span12">
   
    <div class="row-fluid">
      <center>
      
      <ul class="thumbnails">
        <li class="span4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          </div>
        </li>
        
     
        <li class="span4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          </div>
        </li>
        
     
        <li class="span4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          </div>
        </li>
        
      </ul>
    </center>
    </div>
  </div>
</div>


<!--  -->
</div>

app/views/how_it_works/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </a>
      
      <div class="container-fluid nav-collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
           

        
        
        <ul class="nav nav-pills">
                <li><%=link_to "Chef Tutors", root_url %></li>   
                <li><%=link_to "About", abouts_path %></li>               
                <li><%=link_to "How It Works", how_it_works_path %></li>  
                <li><%=link_to "Advertisers", advertisers_path %></li>                
                <li><%=link_to "Developers", developers_path %></li>  
                <li><%=link_to "Careers", careers_path %></li>               
                <li><%=link_to "Team", teams_path %></li>  
                <li><%=link_to "Press", "#" %></li>             
                <li><%=link_to "Contact", contacts_path %></li>  
                <li><%=link_to "Help", helps_path %></li>                     
            
        </ul>          

            
     
        <ul class="nav nav-pills pull-right">           
              
                <li > <%= link_to 'Sign In', "#" %> </li>                
                <li > <%= link_to 'Sign Up', "#" %> </li>      

                
        </ul> 
      
      
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="hero-unit">
  <h1>"How It Works"</h1>
  <p>Tagline</p>
  <p>
    <a class="btn btn-primary btn-large">
      Learn more
    </a>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruffin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
    <div class="row-fluid">    
     
        <%= bootstrap_flash %>
        <%= yield %>
   </div>
 


</body>
</html>